//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeM8Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bills()
        {
            this.BillProcess = new HashSet<BillProcess>();
        }
    
        public int BillID { get; set; }
        public int HomeID { get; set; }
        public int OwnerUserID { get; set; }
        public decimal BillAmount { get; set; }
        public string BillImage { get; set; }
        public System.DateTime LastPayment { get; set; }
        public bool Paid { get; set; }
        public bool State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillProcess> BillProcess { get; set; }
        public virtual Homes Homes { get; set; }
        public virtual Users Users { get; set; }
    }
}
