//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeM8Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvents
    {
        public int CalendarEventID { get; set; }
        public int HomeID { get; set; }
        public Nullable<int> PayerUserID { get; set; }
        public string EventExplanation { get; set; }
        public decimal PaymentAmount { get; set; }
        public bool Paid { get; set; }
        public System.DateTime ExpectedDate { get; set; }
    
        public virtual Homes Homes { get; set; }
        public virtual Users Users { get; set; }
    }
}
