//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeM8Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeM8Entities : DbContext
    {
        public HomeM8Entities()
            : base("name=HomeM8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillProcess> BillProcess { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<CalendarEvents> CalendarEvents { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<ForgotPass> ForgotPass { get; set; }
        public virtual DbSet<FromRegister> FromRegister { get; set; }
        public virtual DbSet<HomeConnections> HomeConnections { get; set; }
        public virtual DbSet<Homes> Homes { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<NotificationComments> NotificationComments { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<RSA> RSA { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Warnings> Warnings { get; set; }
        public virtual DbSet<ConnectionRequests> ConnectionRequests { get; set; }
        public virtual DbSet<HomeUseRules> HomeUseRules { get; set; }
        public virtual DbSet<RuleTypes> RuleTypes { get; set; }
    }
}
