//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeM8Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public int HomeID { get; set; }
        public int OwnerUserID { get; set; }
        public int NotificationType { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ExpectedAnswerRange { get; set; }
    
        public virtual Homes Homes { get; set; }
        public virtual NotificationType NotificationType1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
